### ISSUE TITLE
Exception generating code with combined default and named import

### ISSUE THREAD

**Issue by Conduitry** [Rich-Harris/code-red#3]
```js
print(b`import a, { b } from 'c'`).code
```

throws an exception

```
TypeError: Cannot read property 'type' of undefined
    at handle (.../node_modules/code-red/dist/code-red.js:8:33)
    at .../node_modules/code-red/dist/code-red.js:575:20
    at Array.map (<anonymous>)
    at ImportDeclaration (.../node_modules/code-red/dist/code-red.js:574:41)
    at handle (.../node_modules/code-red/dist/code-red.js:14:10)
```

**Comment by Conduitry** [comment]
I think something like this would do it

```diff
diff --git a/src/print/handlers.ts b/src/print/handlers.ts
index 2d5fb33..fadf8e5 100644
--- a/src/print/handlers.ts
+++ b/src/print/handlers.ts
@@ -644,7 +644,7 @@ const handlers: Record<string, Handler> = {
 
 			if (i < length) {
 				// we have named specifiers
-				const specifiers = node.specifiers.map((specifier: ImportSpecifier) => {
+				const specifiers = node.specifiers.slice(i).map((specifier: ImportSpecifier) => {
 					const name = handle(specifier.imported, state)[0];
 					const as = handle(specifier.local, state)[0];
 
```

Basically, we need to skip over the first `i` specifiers that were already handled up higher. This still feels a little funky though, and the unit tests are confusing me.
