### ISSUE TITLE
Crash with ArrowFunctionExpression as ExpressionStatement

### ISSUE THREAD

**Issue by Conduitry** [Rich-Harris/code-red#38]
```js
cr.print(cr.b`() => {}`).code
```

throws

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at ExpressionStatement (.../code-red/dist/code-red.js:341:49)
    at handle (.../code-red/dist/code-red.js:71:18)
    at .../code-red/dist/code-red.js:249:19
    at Array.map (<anonymous>)
    at handle_body (.../code-red/dist/code-red.js:248:22)
    at Program (.../code-red/dist/code-red.js:319:11)
    at handle (.../code-red/dist/code-red.js:71:18)
    at print (.../code-red/dist/code-red.js:1414:18)
    at Object.print (.../code-red/dist/code-red.js:1399:11)
```

There's apparently an extra situation that needs to be handled [here](https://github.com/Rich-Harris/code-red/blob/2ad7c7a9330bb5c6c75cccda920d5248601ef98b/src/print/handlers.ts#L363) now that `ArrowFunctionExpression` has precedence 3.

Ref. https://github.com/sveltejs/svelte/issues/4617

**Comment by Conduitry** [comment]
Looking at this quickly, there's no reason as far as I can tell to be checking for the precedence of the operator, rather than just checking for the type of the node. So I think we could instead do `node.expression.type === 'AssignmentExpression' && (node.expression as AssignmentExpression).left.type === 'ObjectPattern'`.
